# CatBoost Algorithm
CatBoost is a state-of-the-art open-source gradient boosting on decision trees library. It's simple and easy to use. And is now regularly one of the top algorithms used in data science competitions as it produces very good results without extensive data clean-up or feature engineering.

In [1]:
# import libraries 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
# load the dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [4]:
df.isnull().sum().sort_values(ascending=False)

deck           688
age            177
embarked         2
embark_town      2
survived         0
pclass           0
sex              0
sibsp            0
parch            0
fare             0
class            0
who              0
adult_male       0
alive            0
alone            0
dtype: int64

## Pre-Processing Data

In [5]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)

df['age'] = imputer.fit_transform(df[['age']])
df.drop('deck', axis=1, inplace=True)
# imputing the empty values by using pandas fillna method
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])

In [6]:
# convert all the category and object columns to category columns
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
df[categorical_cols] = df[categorical_cols].astype('category')

In [7]:
# create feature and target or label columns 
X = df.drop('survived', axis=1)
y = df['survived']

# split the dataset into training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
# call the model and fit the model 
model = CatBoostClassifier(iterations=100, learning_rate=0.1, depth=3, loss_function='Logloss', eval_metric='Accuracy')

# fit the model
model.fit(X_train, y_train, cat_features=categorical_cols.to_list())

# predict the model
y_pred = model.predict(X_test)

# evaluate the model
print(f'Accuracy Score: {accuracy_score(y_test, y_pred)}')
print(f'Confusion Matrix: \n {confusion_matrix(y_test, y_pred)}')
print(f'Classification Report: \n {classification_report(y_test, y_pred)}')

0:	learn: 1.0000000	total: 229ms	remaining: 22.6s
1:	learn: 1.0000000	total: 240ms	remaining: 11.8s
2:	learn: 1.0000000	total: 248ms	remaining: 8.03s
3:	learn: 1.0000000	total: 259ms	remaining: 6.23s
4:	learn: 1.0000000	total: 271ms	remaining: 5.14s
5:	learn: 1.0000000	total: 282ms	remaining: 4.42s
6:	learn: 1.0000000	total: 290ms	remaining: 3.85s
7:	learn: 1.0000000	total: 301ms	remaining: 3.46s
8:	learn: 1.0000000	total: 313ms	remaining: 3.16s
9:	learn: 1.0000000	total: 324ms	remaining: 2.91s
10:	learn: 1.0000000	total: 335ms	remaining: 2.71s
11:	learn: 1.0000000	total: 347ms	remaining: 2.54s
12:	learn: 1.0000000	total: 358ms	remaining: 2.4s
13:	learn: 1.0000000	total: 369ms	remaining: 2.27s
14:	learn: 1.0000000	total: 380ms	remaining: 2.15s
15:	learn: 1.0000000	total: 388ms	remaining: 2.03s
16:	learn: 1.0000000	total: 395ms	remaining: 1.93s
17:	learn: 1.0000000	total: 407ms	remaining: 1.85s
18:	learn: 1.0000000	total: 419ms	remaining: 1.78s
19:	learn: 1.0000000	total: 430ms	remaining: 1.72s
20:	learn: 1.0000000	total: 441ms	remaining: 1.66s
21:	learn: 1.0000000	total: 453ms	remaining: 1.61s
22:	learn: 1.0000000	total: 465ms	remaining: 1.55s
23:	learn: 1.0000000	total: 476ms	remaining: 1.51s
24:	learn: 1.0000000	total: 486ms	remaining: 1.46s
25:	learn: 1.0000000	total: 498ms	remaining: 1.42s
26:	learn: 1.0000000	total: 505ms	remaining: 1.36s
27:	learn: 1.0000000	total: 519ms	remaining: 1.33s
28:	learn: 1.0000000	total: 531ms	remaining: 1.3s
29:	learn: 1.0000000	total: 542ms	remaining: 1.26s
30:	learn: 1.0000000	total: 553ms	remaining: 1.23s
31:	learn: 1.0000000	total: 564ms	remaining: 1.2s
32:	learn: 1.0000000	total: 576ms	remaining: 1.17s
33:	learn: 1.0000000	total: 587ms	remaining: 1.14s
34:	learn: 1.0000000	total: 598ms	remaining: 1.11s
35:	learn: 1.0000000	total: 610ms	remaining: 1.08s
36:	learn: 1.0000000	total: 621ms	remaining: 1.06s
37:	learn: 1.0000000	total: 635ms	remaining: 1.03s
38:	learn: 1.0000000	total: 646ms	remaining: 1.01s
39:	learn: 1.0000000	total: 657ms	remaining: 985ms
40:	learn: 1.0000000	total: 666ms	remaining: 958ms
41:	learn: 1.0000000	total: 677ms	remaining: 935ms
42:	learn: 1.0000000	total: 687ms	remaining: 911ms
43:	learn: 1.0000000	total: 699ms	remaining: 889ms
44:	learn: 1.0000000	total: 710ms	remaining: 868ms
45:	learn: 1.0000000	total: 721ms	remaining: 846ms
46:	learn: 1.0000000	total: 732ms	remaining: 825ms
47:	learn: 1.0000000	total: 743ms	remaining: 805ms
48:	learn: 1.0000000	total: 754ms	remaining: 785ms
49:	learn: 1.0000000	total: 765ms	remaining: 765ms
50:	learn: 1.0000000	total: 777ms	remaining: 747ms
51:	learn: 1.0000000	total: 788ms	remaining: 727ms
52:	learn: 1.0000000	total: 799ms	remaining: 709ms
53:	learn: 1.0000000	total: 811ms	remaining: 691ms
54:	learn: 1.0000000	total: 822ms	remaining: 673ms
55:	learn: 1.0000000	total: 833ms	remaining: 655ms
56:	learn: 1.0000000	total: 845ms	remaining: 637ms
57:	learn: 1.0000000	total: 856ms	remaining: 620ms
58:	learn: 1.0000000	total: 868ms	remaining: 603ms
59:	learn: 1.0000000	total: 879ms	remaining: 586ms
60:	learn: 1.0000000	total: 891ms	remaining: 569ms
61:	learn: 1.0000000	total: 901ms	remaining: 552ms
62:	learn: 1.0000000	total: 913ms	remaining: 536ms
63:	learn: 1.0000000	total: 923ms	remaining: 519ms
64:	learn: 1.0000000	total: 934ms	remaining: 503ms
65:	learn: 1.0000000	total: 946ms	remaining: 487ms
66:	learn: 1.0000000	total: 957ms	remaining: 471ms
67:	learn: 1.0000000	total: 967ms	remaining: 455ms
68:	learn: 1.0000000	total: 978ms	remaining: 440ms
69:	learn: 1.0000000	total: 990ms	remaining: 424ms
70:	learn: 1.0000000	total: 1s	remaining: 409ms
71:	learn: 1.0000000	total: 1.01s	remaining: 394ms
72:	learn: 1.0000000	total: 1.02s	remaining: 379ms
73:	learn: 1.0000000	total: 1.03s	remaining: 364ms
74:	learn: 1.0000000	total: 1.04s	remaining: 349ms
75:	learn: 1.0000000	total: 1.06s	remaining: 335ms
76:	learn: 1.0000000	total: 1.07s	remaining: 320ms
77:	learn: 1.0000000	total: 1.08s	remaining: 305ms
78:	learn: 1.0000000	total: 1.09s	remaining: 291ms
79:	learn: 1.0000000	total: 1.1s	remaining: 276ms
80:	learn: 1.0000000	total: 1.11s	remaining: 262ms
81:	learn: 1.0000000	total: 1.13s	remaining: 247ms
82:	learn: 1.0000000	total: 1.14s	remaining: 233ms
83:	learn: 1.0000000	total: 1.15s	remaining: 219ms
84:	learn: 1.0000000	total: 1.16s	remaining: 205ms
85:	learn: 1.0000000	total: 1.18s	remaining: 192ms
86:	learn: 1.0000000	total: 1.19s	remaining: 177ms
87:	learn: 1.0000000	total: 1.2s	remaining: 164ms
88:	learn: 1.0000000	total: 1.21s	remaining: 150ms
89:	learn: 1.0000000	total: 1.22s	remaining: 136ms
90:	learn: 1.0000000	total: 1.23s	remaining: 122ms
91:	learn: 1.0000000	total: 1.24s	remaining: 108ms
92:	learn: 1.0000000	total: 1.26s	remaining: 94.5ms
93:	learn: 1.0000000	total: 1.27s	remaining: 81ms
94:	learn: 1.0000000	total: 1.28s	remaining: 67.4ms
95:	learn: 1.0000000	total: 1.29s	remaining: 54ms
96:	learn: 1.0000000	total: 1.31s	remaining: 40.5ms
97:	learn: 1.0000000	total: 1.32s	remaining: 27ms
98:	learn: 1.0000000	total: 1.37s	remaining: 13.8ms
99:	learn: 1.0000000	total: 1.38s	remaining: 0us
Accuracy Score: 1.0
Confusion Matrix:
 [[105   0]
 [  0  74]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
           1       1.00      1.00      1.00        74

    accuracy                           1.00       179
   macro avg       1.00      1.00      1.00       179
weighted avg       1.00      1.00      1.00       179